name: ci-spell-checking

on:
  push:
    branches: 
    - main
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    branches: 
    - main

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
